
apiVersion: v1
metadata:
  name: Feature XYZ
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
  - ./tests/playwright.test.js
image:
  base: saucelabs/sauce-playwright
  version: 1.0.0
